version: '3.8'
services:
  cache:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - cache:/data
  redis-commander:
    image: rediscommander/redis-commander
    restart: always
    ports:
      - '8081:8081'
    environment:
      - REDIS_HOSTS=local:cache:6379
  broker:
    image: rabbitmq:3.10.10-management-alpine
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
      - '61613:61613'
    volumes:
      - "./rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins"
volumes:
  cache:
    driver: local
